### ISSUE TITLE
POST /gates gabisa (kemarin waktu itu salah naruh)

### ISSUE THREAD

**Issue by jharisonn** [2019-pemrogramanberbasiskerangkakerja-h/secure-gate-system-kelompok_ateng#2]

**Comment by fuaddary** [comment]
sorry for late reply.. bisa dijelaskan lebih rinci permasalahannya? chat line for fast respon :)

**Comment by jharisonn** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/22925976/57984531-d472a400-7a86-11e9-8fc7-6cf417bf9555.png)
![Screenshot_2](https://user-images.githubusercontent.com/22925976/57984532-d50b3a80-7a86-11e9-8e29-3b7df6910f74.png)
![Screenshot_3](https://user-images.githubusercontent.com/22925976/57984533-d50b3a80-7a86-11e9-8cd9-9e0e6a065c30.png)
![Screenshot_4](https://user-images.githubusercontent.com/22925976/57984535-d5a3d100-7a86-11e9-9f67-c636077661cf.png)

oke saya send ke line juga

**Comment by fuaddary** [comment]
typo di dokumentasi... fixed :)
